/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __IMAGE_SIMILARITY_ALL_TYPES_H__
#define __IMAGE_SIMILARITY_ALL_TYPES_H__

#include <image_similarity/types/type_definitions.h>
#include <image_similarity/types/similarity_types.h>


#endif /* __IMAGE_SIMILARITY_ALL_TYPES_H__ */
