/*
 * This file was generated by generate_typesystem.py.
 * Filename:    similarity_types
 * Name:        similarity
 * Description: No description given
 * Version:     1.0
 * Vendor:      None
 */
#ifndef __SIMILARITY_TYPES_H__
#define __SIMILARITY_TYPES_H__

#include <robosherlock/feature_structure_proxy.h>
#include <image_similarity/types/type_definitions.h>
#include <robosherlock/types/core_types.h>

namespace image_similarity
{

/*
 * Data from the internal belief state that corresponds to an object hypothesis
 */
class SimilarityObject : public rs::Annotation
{
private:
  void initFields()
  {
    classification.init(this, "classification");
    matches_surf.init(this, "matches_surf");
    matches_pcl.init(this, "matches_pcl");
    similarityscore_icp.init(this, "similarityscore_icp");
    colorHist_distance.init(this, "colorHist_distance");
  }
public:
  // This is the classification of the rs object
  rs::FeatureStructureEntry<std::string> classification;
  // Amount of matches from surf in 2d
  rs::FeatureStructureEntry<int> matches_surf;
  // Amount of matches from pcl pipeline
  rs::FeatureStructureEntry<int> matches_pcl;
  // Similarityscore from icp
  rs::FeatureStructureEntry<float> similarityscore_icp;
  // float describing the distacne betweeen the rw and bs colorhistogram. filled by clustercolorfrombeliefstate
  rs::FeatureStructureEntry<float> colorHist_distance;

  SimilarityObject(const SimilarityObject &other) :
      rs::Annotation(other)
  {
    initFields();
  }

  SimilarityObject(uima::FeatureStructure fs) :
      rs::Annotation(fs)
  {
    initFields();
  }
};

}

TYPE_TRAIT(image_similarity::SimilarityObject, IMAGE_SIMILARITY_SIMILARITY_SIMILARITYOBJECT)

#endif /* __SIMILARITY_TYPES_H__ */
