/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __IMAGE_SIMILARITY_TYPE_DEFINITIONS_H__
#define __IMAGE_SIMILARITY_TYPE_DEFINITIONS_H__

#define IMAGE_SIMILARITY_SIMILARITY_SIMILARITYOBJECT "image_similarity.similarity.SimilarityObject"

#endif /* __IMAGE_SIMILARITY_TYPE_DEFINITIONS_H__ */
